# .github/release.yml

# This configures GitHub's release note generator:
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes
# See the options here:
# https://docs.github.com/en/repositories/releasing-projects-on-github/automatically-generated-release-notes#configuration-options

changelog:
  exclude:
    labels:
      - ignore-for-release

  categories:
    - title: 🐛 Bug Fixes
      labels:
        - fix
        - bugfix
        - bug
    - title: 🗑 Deprecations
      labels:
        - deprecation
    - title: 🧰 Maintenance
      labels:
        - build
        - ci
        - dependencies
    - title: 🚀 Added
      labels:
        - feature
        - enhancement
        - "*"
